# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use Node.js v14 as the base image
FROM node:14-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy the application source code
COPY src ./src
COPY tsconfig.json ./

# Build the application
RUN npm run build

# Use a minimal Node.js runtime for the final image
FROM node:14-alpine

# Set the working directory
WORKDIR /app

# Copy the built application from the builder stage
COPY --from=builder /app/build ./build

# Set the command to run the application
ENTRYPOINT ["node", "build/index.js"]
